### PR TITLE
Adds settings to hide devices

### PR DESCRIPTION
**Pull request by FL550**
Could this be combined with the existing setting for hiding chromecast devices [here](https://github.com/custom-cards/spotify-card/blob/9b40a0650d9ca931088dead73ee85b03283490fe/src/spotify-card.ts#L310)?

### CODE REVIEW

**Comment by fondberg** [comment]
Sure! Looks right to me. As long as it is a multi select of what devices to filter out I'm fine

**Comment by FL550** [comment]
Wouldn't it be better to change this to a list of excluded devices in freetext form instead of sliders to disable already found devices?
With the current implementation someone who is not using the visual editor can't use this functionality.

**Comment by fondberg** [comment]
Both can be supported. An array in yaml equals an array in js lovelace settings

**Comment by FL550** [comment]
Yes, but right now you have implemented this with checkboxes for already discovered devices. I had to have better clarified that.

As not all devices are visible all the time, I find this not an optimal solution. Wouldn't be a freetext input better, where you can enter the device names directly?

**Comment by fondberg** [comment]
You are right, hmmm, but if it is a list of strings, should we have an array of string patterns instead?
Like 
`[
'*living*',
'*bedroom*'
]`

The hard part is to expose it in an easy way in the config gui...

**Comment by FL550** [comment]
Maybe a comma separated list as input, which is parsed to an array?

**Comment by fondberg** [comment]
Sure but why not an array in both yaml and js?

**Comment by FL550** [comment]
Because I think it would be easier for the users to make a mistake on entering. Having to write
`['*living*', '*bedroom*' ]` is harder than `*living*, *bedroom*`

**Comment by fondberg** [comment]
I see but in yaml an array would  be
```
hidden_devices:
  - livingroom
  - bedroom
```

And in js that will be an array automatically.

**Comment by FL550** [comment]
Ok, i've written an implementation which parses the filters to regex. The filters are separated by a comma, so you can write `.*room` which hides all devices with that name. 

I also included a message if no devices are found at all.

**Comment by fondberg** [comment]
Looks good!

**Pull request merged**
