### PR TITLE
Fixes #76 Add ability to use card multiple times on the same page.

### LINKED ISSUE #76: two playlists on same dashboard?
I tried to create both cards on the same dashboard but the formatting is messed up when having both custom playlists and mixes, is there something i'm missing here?

client_id: ID
name: Spotify 1
id: 211
dailyMixes: true
device: null
featuredPlaylists: null
featuredPlaylistsCountryCode: us
height: 240
limit: 20
player: null
random_song: null
type: 'custom:spotify-card'
- client_id: ID
name: Spotify 2
dailyMixes: false
device: null
featuredPlaylists: null
featuredPlaylistsCountryCode: us
height: 720
limit: 20
player: null
random_song: true
type: 'custom:spotify-card'

### PR DESCRIPTION
**Pull request by FL550**
Fixes #76 With this change the style node is correctly applied on multiple cards, so different modes of the same card can be used.

### CODE REVIEW

**Comment by FL550** [comment]
I've also struggled a few hours before. But then I stumbled over an article from Mozilla and found this solution. 

Great to hear you are working on a new version! Let me know if I can help, I have a lot of free time right now.

**Comment by fondberg** [comment]
Sounds good. Help is always appreciated.

I want to remove direct calls to spotify web api for the card. I just implemented web service api in spotcast to return all different playlists. Then I want to make use of the spotify media player wrt to playback state  and pause. And use spotcast to initiate play back.

I am also pondering if the styling should be more HASS lovelace... wdyt?

**Comment by FL550** [comment]
I just sent you an email. 

Whats the benefit of removing the direct calls? Right now, if a user has no chromecast, he doesn't need spotcast to use this card.

About the styling: yes I think it should follow the main theme a little bit more. So on default a lighter version with option to select a "dark mode" would be best.

**Comment by fondberg** [comment]
Added this PR in https://github.com/custom-cards/spotify-card/releases/tag/v1.27.1

**Pull request closed without merging**
