### PR TITLE
Add Playlist Shuffle

### PR DESCRIPTION
**Pull request by jacobswe**
Adds separate shuffle option to choose random songs within playlist. With this option, playlist will still start at first song, then shuffle. In tandem with random_song allows for full shuffling.

### CODE REVIEW

**Comment by fondberg** [comment]
Hi, something must have gone wrong because all I can see are two changed files and a whole lot of commits which are not part of this PR.

A note though, if you do add shuffle so it makes it in it will only be for spotcast unless you add functionality to two places

**Comment by fondberg** [comment]
I've been off sick so I have not had time to look at this. Sorry about that.

I don't want the shuffle happen as an extra api call every time the user clicks on a playlist. 

Also there still seems to be missing code to pass this from the Custom elelement to the react component.

**Comment by jacobswe** [comment]
Hi, please do not worry over this. My bad for leaving this open for so long. I will rewrite and try to make it work with both Spotify API and spotcast, just have not found time to do testing yet.

**Comment by fondberg** [comment]
I'm closing this for now. Feel free to repopen it when you have time to fix the things.

**Pull request closed without merging**
