### PR TITLE
Filtering by device type

### PR DESCRIPTION
**Pull request by mbw2001**
I never use Spotify Connect, and many of my devices are both Chromecast and Connect devices so I cannot filter by name.

So I created this to support filtering out all the Connect devices from the list. I also added support for filtering out the Chromecast devices in a similar manner.

It was created for my own benefit, but thought I would create this PR in case you found it relevant to other users as well.

### CODE REVIEW

**Comment by FL550** [comment]
Hey, thanks for your contribution! The first commit looks great. I will merge this in the next days.

But as you also simplified the settings (thank you very much for this also) in this PR and these are a lot of changes, I have to check these first before accepting the PR.

**Comment by mbw2001** [comment]
Oh. I forgot to create a new branch and it was merged into the same PR. The settings was supposed to be another PR later. Sorry about that.

**Comment by FL550** [comment]
This is no problem. But it'll take me a bit more time to review 😉

**Comment by FL550** [comment]
Looks good, thank you very much!

**Pull request merged**
